"""
Interview Summary Generator (Day 39)

WHAT THIS DAY ADDS: Days 34-38 produce rich structured data --
answer-quality tiers, communication scores, confidence/stress
signals, a weighted HR score, an aptitude profile -- but none of it is
in a form a recruiter can actually read in thirty seconds. This day
is the final translation layer: it takes Day 37's `HRInterviewScoreReport`
(itself already an aggregate of Days 34-36) and, optionally, Day 38's
`AptitudeProfile` and Day 36's `InterviewConfidenceProfile`, and turns
them into the five things the brief asks for -- strengths, weaknesses,
cultural fit indicators, risk flags, and a natural-language narrative
-- reusing every underlying number rather than recomputing any of it.

REUSE, NOT REIMPLEMENTATION: every score this module reports on is
read directly from Day 37's `HRInterviewScoreReport` (relevance,
communication, confidence, consistency findings, per-answer
breakdowns including relevance tier and category), Day 38's
`AptitudeProfile` (reasoning/situational scores), and, if supplied,
Day 36's `InterviewConfidenceProfile` (stress score, for the one risk
flag that needs it and that Day 37's aggregate doesn't carry forward).
Nothing here re-derives a signal -- this module's only new logic is
CLASSIFICATION (turning a number into "strength" or "weakness" against
a threshold) and TEXT GENERATION (turning a classification into a
sentence).

NATURAL-LANGUAGE GENERATION, STATED HONESTLY: "generate natural-
language report" here means TEMPLATE-BASED sentence generation --
a fixed set of sentence templates selected by which score band a
number falls into, the same deterministic, rule-based approach every
other module in this project uses. This is NOT a generative language
model summarizing free-form -- this project has no LLM integration
built anywhere, and this day does not introduce one. The output reads
naturally because the templates were written to, not because
anything was generated by a model. Named here rather than implied by
"AI interview report generator."

CULTURAL FIT INDICATORS, STATED HONESTLY: the only direct signal this
project has for "culture fit" is performance on the single
`teamwork_culture_fit` category question(s) from the HR interview
(Day 33's question bank). This is a narrow proxy -- one or two answers
about teamwork are not a real culture-fit assessment, which would
need much more (values alignment, work-style preferences, references)
than a rule-based text project can produce. Reported as an
"indicator", never as a verdict.

RISK FLAGS, STATED HONESTLY: each flag here is a MECHANICAL threshold
trigger on an existing signal (a vague/missing answer, a flagged
inconsistency, elevated stress, weak aptitude) -- not a judgment about
the candidate as a person. Flags are reported with the specific
evidence behind them so a recruiter can check the reasoning, not just
trust a label.

THRESHOLDS: all score-band and flag thresholds are named module-level
constants, reasoned but NOT calibrated against labeled hiring
outcomes -- no such data exists in this project, the same caveat
stated on every prior scoring day (34-38). Adjustable by changing the
constants; no separate config object was built for this day since,
unlike Day 37's four-parameter weighting, there is only one knob per
threshold here.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional

from parsers.hr_interview_scoring_engine import HRInterviewScoreReport
from parsers.aptitude_logic_engine import AptitudeProfile
from parsers.confidence_stress_engine import InterviewConfidenceProfile

_STRONG_THRESHOLD = 80.0
_WEAK_THRESHOLD = 50.0
_STRESS_ELEVATED_THRESHOLD = 50.0
_APTITUDE_OVERALL_WEIGHT = 0.3   # combined_overall_score = 70% HR score + 30% aptitude, when aptitude is supplied
_HR_OVERALL_WEIGHT = 0.7

_PERFORMANCE_BANDS = [
    (80.0, "Strong"),
    (65.0, "Good"),
    (50.0, "Moderate"),
    (0.0, "Weak"),
]

_COMPONENT_LABELS = {
    "relevance": "answer relevance",
    "communication": "communication",
    "confidence": "confidence",
    "aptitude": "aptitude / logical reasoning",
}


def _band_for_score(score: float) -> str:
    for threshold, label in _PERFORMANCE_BANDS:
        if score >= threshold:
            return label
    return "Weak"


# ---------------------------------------------------------------------------
# Strengths / weaknesses -- classification against Day 37/38's own scores
# ---------------------------------------------------------------------------

@dataclass
class ScoredNote:
    component: str
    score: float
    note: str


def _classify_components(hr_report: HRInterviewScoreReport, aptitude_profile: Optional[AptitudeProfile]) -> (List[ScoredNote], List[ScoredNote]):
    strengths: List[ScoredNote] = []
    weaknesses: List[ScoredNote] = []

    component_scores = {
        "relevance": hr_report.avg_relevance,
        "communication": hr_report.avg_communication,
        "confidence": hr_report.avg_confidence,
    }
    if aptitude_profile is not None and aptitude_profile.answer_evaluations:
        component_scores["aptitude"] = aptitude_profile.overall_aptitude_score

    for component, score in component_scores.items():
        label = _COMPONENT_LABELS[component]
        if score >= _STRONG_THRESHOLD:
            strengths.append(ScoredNote(component, score, f"Demonstrated strong {label} ({score}/100)."))
        elif score < _WEAK_THRESHOLD:
            weaknesses.append(ScoredNote(component, score, f"Showed weak {label} ({score}/100) -- worth probing further."))
        # scores in between are intentionally left unlisted -- middling
        # performance is not a strength or a weakness worth flagging.

    return strengths, weaknesses


# ---------------------------------------------------------------------------
# Cultural fit indicator -- a narrow, explicitly-scoped proxy
# ---------------------------------------------------------------------------

@dataclass
class CulturalFitIndicator:
    score: Optional[float]
    band: str
    note: str


def _assess_cultural_fit(hr_report: HRInterviewScoreReport) -> CulturalFitIndicator:
    culture_breakdowns = [b for b in hr_report.answer_breakdowns if b.category == "teamwork_culture_fit"]

    if not culture_breakdowns:
        return CulturalFitIndicator(
            score=None, band="no signal",
            note="No teamwork/culture-fit question was answered in this session -- no indicator available.",
        )

    avg_score = round(sum(b.weighted_positive_component for b in culture_breakdowns) / len(culture_breakdowns), 1)
    if avg_score >= _STRONG_THRESHOLD:
        band, note = "positive indicator", f"Teamwork/culture-fit response scored {avg_score}/100 -- a positive signal, though based on a single question and not a full culture-fit assessment."
    elif avg_score < _WEAK_THRESHOLD:
        band, note = "needs attention", f"Teamwork/culture-fit response scored {avg_score}/100 -- worth exploring further in a follow-up conversation."
    else:
        band, note = "neutral", f"Teamwork/culture-fit response scored {avg_score}/100 -- no strong signal either way."

    return CulturalFitIndicator(score=avg_score, band=band, note=note)


# ---------------------------------------------------------------------------
# Risk flags -- mechanical threshold triggers, evidence attached
# ---------------------------------------------------------------------------

@dataclass
class RiskFlag:
    label: str
    detail: str


def _detect_risk_flags(
    hr_report: HRInterviewScoreReport, aptitude_profile: Optional[AptitudeProfile], confidence_profile: Optional[InterviewConfidenceProfile],
) -> List[RiskFlag]:
    flags: List[RiskFlag] = []

    weak_answers = [b for b in hr_report.answer_breakdowns if b.relevance_quality in ("vague", "missing")]
    if weak_answers:
        ids = ", ".join(b.question_id for b in weak_answers)
        flags.append(RiskFlag(
            "Vague or missing answer content",
            f"{len(weak_answers)} answer(s) rated vague/missing on relevance: {ids}.",
        ))

    if hr_report.consistency.findings:
        flags.append(RiskFlag(
            "Possible response inconsistency",
            f"{len(hr_report.consistency.findings)} finding(s) flagged (not confirmed contradictions): " + "; ".join(hr_report.consistency.findings),
        ))

    if confidence_profile is not None and confidence_profile.answer_evaluations:
        if confidence_profile.overall_stress_score >= _STRESS_ELEVATED_THRESHOLD:
            flags.append(RiskFlag(
                "Elevated stress-indicative language",
                f"Overall linguistic stress proxy score: {confidence_profile.overall_stress_score}/100 (see Day 36 -- a linguistic proxy, not a physiological measurement).",
            ))

    if aptitude_profile is not None and aptitude_profile.answer_evaluations:
        if aptitude_profile.overall_aptitude_score < _WEAK_THRESHOLD:
            flags.append(RiskFlag(
                "Weak logical reasoning performance",
                f"Overall aptitude score: {aptitude_profile.overall_aptitude_score}/100 (reasoning avg {aptitude_profile.logical_reasoning_avg}, situational avg {aptitude_profile.situational_judgment_avg}).",
            ))

    return flags


# ---------------------------------------------------------------------------
# Full summary report -- the "AI interview report generator" +
# "structured summary template" deliverables
# ---------------------------------------------------------------------------

@dataclass
class InterviewSummaryReport:
    combined_overall_score: float
    performance_band: str
    hr_score: float
    aptitude_score: Optional[float]
    strengths: List[ScoredNote]
    weaknesses: List[ScoredNote]
    cultural_fit: CulturalFitIndicator
    risk_flags: List[RiskFlag]

    def to_dict(self) -> Dict:
        return {
            "combined_overall_score": self.combined_overall_score,
            "performance_band": self.performance_band,
            "hr_score": self.hr_score,
            "aptitude_score": self.aptitude_score,
            "strengths": [{"component": s.component, "score": s.score, "note": s.note} for s in self.strengths],
            "weaknesses": [{"component": w.component, "score": w.score, "note": w.note} for w in self.weaknesses],
            "cultural_fit": {"score": self.cultural_fit.score, "band": self.cultural_fit.band, "note": self.cultural_fit.note},
            "risk_flags": [{"label": r.label, "detail": r.detail} for r in self.risk_flags],
        }

    def to_narrative(self) -> str:
        """The 'generate natural-language report' deliverable --
        template-based, not model-generated (see module docstring)."""
        lines = [
            "Interview Summary Report",
            "=" * 40,
            f"Overall Performance: {self.performance_band} ({self.combined_overall_score}/100)",
            f"  HR interview score: {self.hr_score}/100" + (f" | Aptitude score: {self.aptitude_score}/100" if self.aptitude_score is not None else ""),
            "",
        ]

        lines.append("Strengths:")
        if self.strengths:
            for s in self.strengths:
                lines.append(f"  - {s.note}")
        else:
            lines.append("  - No standout strengths identified above the reporting threshold.")

        lines.append("")
        lines.append("Weaknesses:")
        if self.weaknesses:
            for w in self.weaknesses:
                lines.append(f"  - {w.note}")
        else:
            lines.append("  - No significant weaknesses identified below the reporting threshold.")

        lines.append("")
        lines.append(f"Cultural Fit Indicator ({self.cultural_fit.band}):")
        lines.append(f"  - {self.cultural_fit.note}")

        lines.append("")
        lines.append("Risk Flags:")
        if self.risk_flags:
            for r in self.risk_flags:
                lines.append(f"  - [{r.label}] {r.detail}")
        else:
            lines.append("  - None identified.")

        return "\n".join(lines)


def generate_interview_summary(
    hr_report: HRInterviewScoreReport,
    aptitude_profile: Optional[AptitudeProfile] = None,
    confidence_profile: Optional[InterviewConfidenceProfile] = None,
) -> InterviewSummaryReport:
    strengths, weaknesses = _classify_components(hr_report, aptitude_profile)
    cultural_fit = _assess_cultural_fit(hr_report)
    risk_flags = _detect_risk_flags(hr_report, aptitude_profile, confidence_profile)

    aptitude_score = aptitude_profile.overall_aptitude_score if (aptitude_profile and aptitude_profile.answer_evaluations) else None

    if aptitude_score is not None:
        combined = round(hr_report.overall_hr_score * _HR_OVERALL_WEIGHT + aptitude_score * _APTITUDE_OVERALL_WEIGHT, 1)
    else:
        combined = hr_report.overall_hr_score

    return InterviewSummaryReport(
        combined_overall_score=combined, performance_band=_band_for_score(combined),
        hr_score=hr_report.overall_hr_score, aptitude_score=aptitude_score,
        strengths=strengths, weaknesses=weaknesses, cultural_fit=cultural_fit, risk_flags=risk_flags,
    )
